services:
  mysql80:
    image: mysql:8.0.37
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Tokyo
    command: --innodb-use-native-aio=0
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    volumes:
      - type: volume
        source: mysql80
        target: /var/lib/mysql
    networks:
      - shark

  mysql57:
    image: mysql:5.7.40
    platform: linux/amd64
    ports:
      - "3307:3306"
    expose:
      - "3307"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_TCP_PORT=3307
      - TZ=Asia/Tokyo
    command: --innodb-use-native-aio=0
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    volumes:
      - type: volume
        source: mysql57
        target: /var/lib/mysql
    networks:
      - shark

volumes:
  mysql80:
    external: true
  mysql57:
    external: true

networks:
  shark:
    external: true
